use heroku_142de0a726b37cc;

DROP TABLE IF EXISTS history;
DROP TABLE IF EXISTS tournament;
DROP TABLE IF EXISTS arbitre;
DROP TABLE IF EXISTS matchs;
DROP TABLE IF EXISTS SPORT;

/*CREATE TABLE history (
  id INT AUTO_INCREMENT NOT NULL,
  idMatch INT NOT NULL,
  equipe VARCHAR(128) NOT NULL,
  eventType VARCHAR(128) NOT NULL,
  eventMatch VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`)
);*/

CREATE TABLE history (
  id         INT AUTO_INCREMENT NOT NULL,
  evenement      VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE tournament (
  id INT AUTO_INCREMENT NOT NULL,
  nameTournament VARCHAR(50) NOT NULL,
  sport VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE arbitre (
  id INT AUTO_INCREMENT NOT NULL,
  nameArbitre VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE matchs (
  id INT AUTO_INCREMENT NOT NULL,
  equipeA VARCHAR(50) NOT NULL,
  equipeB VARCHAR(50) NOT NULL,
  idTournament INT,
  PRIMARY KEY (`id`)
);

CREATE TABLE SPORT (
  id VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`)
);