version: '2'

services:
  db:
    image: mysql:latest # use latest version of mysql
    container_name: "db"
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: testdb # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
  go:
    container_name:  "server"
    restart: always
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      
volumes:
  my-db: