DROP TABLE IF EXISTS history;

CREATE TABLE history (
  id INT AUTO_INCREMENT NOT NULL,
  idMatch INT NOT NULL,
  equipe VARCHAR(128) NOT NULL,
  eventType VARCHAR(128) NOT NULL,
  eventMatch VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`)
);